import type { CatalogPack } from "../types/box";
import type { StoreItem, StoreRarity } from "../types/store";
import { NBA_BOX_POOLS } from "../data/boxItems";
import { NFL_ITEMS } from "./nflItems";
import { MLB_ITEMS } from "./mlbItems";
import {
  DUELISTS_VAULT_ITEM_IDS,
  EXODIA_PIECE_ITEM_IDS,
  FORBIDDEN_RITE_ITEM_IDS,
  YUGIOH_GENERAL_POOL,
} from "./categoryPools";
import { SPORTS_PLACEHOLDER_IMAGE } from "./sportsAssets";
import { YUGIOH_LOBBY_COVERS, yugiohLobbyCover } from "./yugiohAssets";

const PACK_PLACEHOLDER = "/images/placeholder-pack.svg";

function allItemIds(catalog: StoreItem[]): string[] {
  return catalog.map((item) => item.id);
}

function itemIdsByRarity(
  catalog: StoreItem[],
  tiers: readonly StoreRarity[],
): string[] {
  const allowed = new Set(tiers);
  return catalog.filter((item) => allowed.has(item.rarity)).map((item) => item.id);
}

/** NBA basketball mystery boxes — sorted low → high gem cost for lobby rows. */
export const NBA_LOBBY_PACKS: CatalogPack[] = [
  {
    id: "rookie-wire-starter",
    name: "Rookie Wire Starter Box",
    cost: 500,
    theme: "gold",
    description: "Budget hardwood entry — modern rookies and silver Prizm hits.",
    category: "nba",
    visual: "nba-hardwood",
    image: PACK_PLACEHOLDER,
    items: [...NBA_BOX_POOLS["rookie-wire-starter"]],
    accentLabel: "BUDGET TIER",
  },
  {
    id: "prizm-silver-surge",
    name: "Prizm Silver Surge Pack",
    cost: 1_200,
    theme: "gold",
    description: "Chase silver parallels and optic holos from the last five seasons.",
    category: "nba",
    visual: "nba-hardwood",
    image: PACK_PLACEHOLDER,
    items: [...NBA_BOX_POOLS["prizm-silver-surge"]],
    accentLabel: "MID TIER",
  },
  {
    id: "court-side-autograph",
    name: "Court-Side Autograph Edition",
    cost: 2_500,
    theme: "fuchsia",
    description: "On-card autos and game-worn patch slabs from hardwood icons.",
    category: "nba",
    visual: "nba-hardwood",
    image: PACK_PLACEHOLDER,
    items: [...NBA_BOX_POOLS["court-side-autograph"]],
    accentLabel: "🔥 TRENDING",
  },
  {
    id: "playoff-pressure",
    name: "Playoff Pressure Pack",
    cost: 3_000,
    theme: "fuchsia",
    description: "Postseason heat — rookies and legends.",
    category: "nba",
    visual: "nba-hardwood",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: [...NBA_BOX_POOLS["playoff-pressure"]],
    accentLabel: "⚡ HIGH VARIANCE",
  },
  {
    id: "all-star-hardwood",
    name: "All-Star Hardwood Drop",
    cost: 5_000,
    theme: "gold",
    description: "Court-ready slabs and signed hardwood hits.",
    category: "nba",
    visual: "nba-hardwood",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: [...NBA_BOX_POOLS["all-star-hardwood"]],
    accentLabel: "🔥 TRENDING",
  },
  {
    id: "dynasty-chrome-vault",
    name: "Dynasty Chrome Vault",
    cost: 7_500,
    theme: "mystic",
    description: "Premium chrome and numbered parallels with grail ceiling potential.",
    category: "nba",
    visual: "nba-hardwood",
    image: PACK_PLACEHOLDER,
    items: [...NBA_BOX_POOLS["dynasty-chrome-vault"]],
    accentLabel: "1,000x CEILING",
  },
  {
    id: "hardwood-grail-hunter",
    name: "Hardwood Grail Hunter",
    cost: 10_000,
    theme: "mystic",
    description: "Ultra-premium PSA slabs — LeBron, Kobe, and generational chase cards.",
    category: "nba",
    visual: "nba-hardwood",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: [...NBA_BOX_POOLS["hardwood-grail-hunter"]],
    accentLabel: "1,000x CEILING",
  },
];

/** NFL football mystery boxes. */
export const NFL_LOBBY_PACKS: CatalogPack[] = [
  {
    id: "red-zone-ripper",
    name: "Red Zone Ripper Box",
    cost: 500,
    theme: "gold",
    description: "Sunday entry tier — optic holos and rookie Prizm staples.",
    category: "nfl",
    image: PACK_PLACEHOLDER,
    items: itemIdsByRarity(NFL_ITEMS, ["Rare", "Epic", "Common"]),
    accentLabel: "BUDGET TIER",
  },
  {
    id: "draft-day-spark",
    name: "Draft Day Spark Pack",
    cost: 1_500,
    theme: "gold",
    description: "First-year RC heat from Panini Prizm and Optic chrome runs.",
    category: "nfl",
    image: PACK_PLACEHOLDER,
    items: itemIdsByRarity(NFL_ITEMS, ["Epic", "Rare", "Common"]),
    accentLabel: "MID TIER",
  },
  {
    id: "championship-drive",
    name: "Championship Drive Edition",
    cost: 2_500,
    theme: "fuchsia",
    description: "Playoff patches and ticket stubs from title-winning seasons.",
    category: "nfl",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: itemIdsByRarity(NFL_ITEMS, ["Legendary", "Epic", "Rare"]),
    accentLabel: "🔥 TRENDING",
  },
  {
    id: "gridiron-legends",
    name: "Gridiron Legends Box",
    cost: 4_000,
    theme: "gold",
    description: "Helmet patches and championship relics.",
    category: "nfl",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: allItemIds(NFL_ITEMS),
    accentLabel: "🔥 TRENDING",
  },
  {
    id: "sunday-max",
    name: "Sunday Max Volatility",
    cost: 6_500,
    theme: "mystic",
    description: "High-variance football grails for serious collectors.",
    category: "nfl",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: itemIdsByRarity(NFL_ITEMS, ["Mythic", "Legendary", "Epic"]),
    accentLabel: "1,000x CEILING",
  },
  {
    id: "super-bowl-relic",
    name: "Super Bowl Relic Vault",
    cost: 8_500,
    theme: "mystic",
    description: "Game-used memorabilia and ticket slabs from Lombardi moments.",
    category: "nfl",
    image: PACK_PLACEHOLDER,
    items: itemIdsByRarity(NFL_ITEMS, ["Mythic", "Legendary"]),
    accentLabel: "⚡ HIGH VARIANCE",
  },
  {
    id: "gridiron-grail-chase",
    name: "Gridiron Grail Chase",
    cost: 10_000,
    theme: "mystic",
    description: "Mahomes, Brady, and Burrow PSA 10 ceiling hunts.",
    category: "nfl",
    image: PACK_PLACEHOLDER,
    items: itemIdsByRarity(NFL_ITEMS, ["Mythic", "Legendary"]),
    accentLabel: "1,000x CEILING",
  },
];

/** MLB baseball mystery boxes. */
export const MLB_LOBBY_PACKS: CatalogPack[] = [
  {
    id: "diamond-debut-starter",
    name: "Diamond Debut Starter",
    cost: 500,
    theme: "gold",
    description: "Bowman Chrome rookies and Topps Series 1 staples for new collectors.",
    category: "mlb",
    image: PACK_PLACEHOLDER,
    items: itemIdsByRarity(MLB_ITEMS, ["Rare", "Epic", "Common"]),
    accentLabel: "BUDGET TIER",
  },
  {
    id: "rookie-pipeline-drop",
    name: "Rookie Pipeline Drop",
    cost: 1_200,
    theme: "gold",
    description: "Prospect chrome and pipeline parallels from the minors to the show.",
    category: "mlb",
    image: PACK_PLACEHOLDER,
    items: itemIdsByRarity(MLB_ITEMS, ["Epic", "Rare", "Common"]),
    accentLabel: "MID TIER",
  },
  {
    id: "all-star-slab-series",
    name: "All-Star Slab Series",
    cost: 2_500,
    theme: "fuchsia",
    description: "Midsummer classic hits — autos, patches, and numbered refractors.",
    category: "mlb",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: itemIdsByRarity(MLB_ITEMS, ["Legendary", "Epic", "Rare"]),
    accentLabel: "🔥 TRENDING",
  },
  {
    id: "world-series-memorabilia",
    name: "World Series Memorabilia Box",
    cost: 4_000,
    theme: "gold",
    description: "Fall classic relics and ticket stubs from October legends.",
    category: "mlb",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: allItemIds(MLB_ITEMS),
    accentLabel: "⚡ HIGH VARIANCE",
  },
  {
    id: "chrome-kings-vault",
    name: "Chrome Kings Vault",
    cost: 6_500,
    theme: "mystic",
    description: "Bowman Chrome 1sts and refractor kings with serious gem upside.",
    category: "mlb",
    image: PACK_PLACEHOLDER,
    items: itemIdsByRarity(MLB_ITEMS, ["Mythic", "Legendary", "Epic"]),
    accentLabel: "1,000x CEILING",
  },
  {
    id: "cooperstown-grail-hunter",
    name: "Cooperstown Grail Hunter",
    cost: 10_000,
    theme: "mystic",
    description: "Ohtani, Trout, and Judge PSA slabs — the diamond ceiling tier.",
    category: "mlb",
    image: SPORTS_PLACEHOLDER_IMAGE,
    items: itemIdsByRarity(MLB_ITEMS, ["Mythic", "Legendary"]),
    accentLabel: "1,000x CEILING",
  },
];

/** Yu-Gi-Oh! mystery boxes. */
export const YUGIOH_LOBBY_PACKS: CatalogPack[] = [
  {
    id: "duelist-starter-cache",
    name: "Duelist Starter Cache",
    cost: 500,
    theme: "gold",
    description: "Classic commons and rare spell staples for new duelists.",
    category: "yugioh",
    image: yugiohLobbyCover("duelist-starter-cache"),
    items: itemIdsByRarity(YUGIOH_GENERAL_POOL, ["Rare", "Common"]),
    accentLabel: "BUDGET TIER",
  },
  {
    id: "legacy-collection-raid",
    name: "Legacy Collection Raid",
    cost: 1_500,
    theme: "gold",
    description: "LOB and early-set holos with tournament-ready rare pulls.",
    category: "yugioh",
    image: yugiohLobbyCover("legacy-collection-raid"),
    items: itemIdsByRarity(YUGIOH_GENERAL_POOL, ["Epic", "Rare", "Common"]),
    accentLabel: "MID TIER",
  },
  {
    id: "shadow-rare-hunt",
    name: "Shadow Rare Hunt",
    cost: 2_500,
    theme: "fuchsia",
    description: "Ghost rares and ultimate rare chase cards from iconic sets.",
    category: "yugioh",
    image: yugiohLobbyCover("shadow-rare-hunt"),
    items: itemIdsByRarity(YUGIOH_GENERAL_POOL, ["Epic", "Rare"]),
    accentLabel: "⚡ HIGH VARIANCE",
  },
  {
    id: "duelists-vault",
    name: "Duelist's Secret Vault",
    cost: 3_500,
    theme: "mystic",
    description:
      "Iconic retro powerhouse singles — Blue-Eyes, Dark Magician, Red-Eyes, Summoned Skull, and Time Wizard.",
    category: "yugioh",
    image: YUGIOH_LOBBY_COVERS["duelists-vault"],
    items: [...DUELISTS_VAULT_ITEM_IDS],
    accentLabel: "⚡ HIGH VARIANCE",
  },
  {
    id: "toon-chaos-edition",
    name: "Toon Chaos Edition",
    cost: 4_500,
    theme: "fuchsia",
    description: "Toon and chaos archetype supremacy with high-variance spell hits.",
    category: "yugioh",
    image: yugiohLobbyCover("toon-chaos-edition"),
    items: itemIdsByRarity(YUGIOH_GENERAL_POOL, ["Epic", "Rare", "Common"]),
    accentLabel: "🔥 TRENDING",
  },
  {
    id: "exodia-chase-protocol",
    name: "Exodia Chase Protocol",
    cost: 7_500,
    theme: "mystic",
    description: "Forbidden one pieces and LOB 1st edition mythic ceiling hunts.",
    category: "yugioh",
    image: yugiohLobbyCover("exodia-chase-protocol"),
    items: [...EXODIA_PIECE_ITEM_IDS],
    accentLabel: "1,000x CEILING",
  },
  {
    id: "forbidden-rite",
    name: "Forbidden Rite Edition",
    cost: 8_000,
    theme: "fuchsia",
    description:
      "Maximum grail hunt — complete Exodia limbs, Jinzo, and Cyber Dragon. No overlap with the Vault box.",
    category: "yugioh",
    image: YUGIOH_LOBBY_COVERS["forbidden-rite"],
    items: [...FORBIDDEN_RITE_ITEM_IDS],
    accentLabel: "1,000x CEILING",
  },
  {
    id: "millennium-tin-premium",
    name: "Millennium Tin Premium",
    cost: 9_500,
    theme: "mystic",
    description: "Tin-era ultra rares and ghost rare grails for elite collectors.",
    category: "yugioh",
    image: yugiohLobbyCover("millennium-tin-premium"),
    items: itemIdsByRarity(YUGIOH_GENERAL_POOL, ["Epic", "Rare", "Common"]),
    accentLabel: "1,000x CEILING",
  },
];
