/**
 * Launch Pokémon catalog — pack-specific registries (~25 cards each).
 * Card data lives in `packPokemonPools.ts`; packs whitelist IDs in `packs.ts`.
 */
import type { StoreItem } from "../types/store";
import {
  ALL_PACK_POKEMON_ITEMS,
  TRAINERS_STARTER_POOL,
  PACK_151_POOL,
  LEGENDARY_HUNT_POOL,
  GOD_PACK_1999_POOL,
  MEGA_EVOLUTION_POOL,
  PRISMATIC_SIR_POOL,
  EVOLVING_SKIES_POOL,
  WOTC_FIRST_EDITION_POOL,
  OBSIDIAN_VAULT_POOL,
  PSA_10_CHASER_POOL,
  WAIFU_VAULT_POOL,
  SHINY_VAULT_POOL,
  POWER_HOUR_POOL,
  MIDNIGHT_GRAIL_POOL,
  FLASH_POOL,
  WEEKEND_WARRIOR_POOL,
  TRAINERS_STARTER_ITEM_IDS,
  PACK_151_ITEM_IDS,
  LEGENDARY_HUNT_ITEM_IDS,
  GOD_PACK_1999_ITEM_IDS,
  MEGA_EVOLUTION_ITEM_IDS,
  PRISMATIC_SIR_ITEM_IDS,
  EVOLVING_SKIES_ITEM_IDS,
  WOTC_FIRST_EDITION_ITEM_IDS,
  OBSIDIAN_VAULT_ITEM_IDS,
  PSA_10_CHASER_ITEM_IDS,
  WAIFU_VAULT_ITEM_IDS,
  SHINY_VAULT_ITEM_IDS,
  POWER_HOUR_ITEM_IDS,
  MIDNIGHT_GRAIL_ITEM_IDS,
  FLASH_ITEM_IDS,
  WEEKEND_WARRIOR_ITEM_IDS,
  storeItemToCard,
} from "./packPokemonPools";
import { ALL_INFINITE_SERIES_ITEMS } from "./infiniteSeriesPools";

export {
  TRAINERS_STARTER_POOL,
  PACK_151_POOL,
  LEGENDARY_HUNT_POOL,
  GOD_PACK_1999_POOL,
  MEGA_EVOLUTION_POOL,
  PRISMATIC_SIR_POOL,
  EVOLVING_SKIES_POOL,
  WOTC_FIRST_EDITION_POOL,
  OBSIDIAN_VAULT_POOL,
  PSA_10_CHASER_POOL,
  WAIFU_VAULT_POOL,
  SHINY_VAULT_POOL,
  POWER_HOUR_POOL,
  MIDNIGHT_GRAIL_POOL,
  FLASH_POOL,
  WEEKEND_WARRIOR_POOL,
  TRAINERS_STARTER_ITEM_IDS,
  PACK_151_ITEM_IDS,
  LEGENDARY_HUNT_ITEM_IDS,
  GOD_PACK_1999_ITEM_IDS,
  MEGA_EVOLUTION_ITEM_IDS,
  PRISMATIC_SIR_ITEM_IDS,
  EVOLVING_SKIES_ITEM_IDS,
  WOTC_FIRST_EDITION_ITEM_IDS,
  OBSIDIAN_VAULT_ITEM_IDS,
  PSA_10_CHASER_ITEM_IDS,
  WAIFU_VAULT_ITEM_IDS,
  SHINY_VAULT_ITEM_IDS,
  POWER_HOUR_ITEM_IDS,
  MIDNIGHT_GRAIL_ITEM_IDS,
  FLASH_ITEM_IDS,
  WEEKEND_WARRIOR_ITEM_IDS,
  storeItemToCard,
};

export const POKEMON_ITEMS: StoreItem[] = [
  ...ALL_PACK_POKEMON_ITEMS,
  ...ALL_INFINITE_SERIES_ITEMS,
];

export const POKEMON_CARD_POOL = POKEMON_ITEMS.map(storeItemToCard);
export const POKEMON_ALL_ITEM_IDS: string[] = POKEMON_ITEMS.map((item) => item.id);
export const POKEMON_MYTHIC_LEGENDARY_IDS: string[] = POKEMON_ITEMS.filter(
  (item) => item.rarity === "Mythic" || item.rarity === "Legendary",
).map((item) => item.id);
