import type { VaultedCard } from "../types";

/** Premium Pokémon vault mock — direct TCG API art URLs. */
export const VAULT_ITEMS: VaultedCard[] = [
  {
    vaultId: "v1",
    id: "pk-vault-charizard-ex",
    name: "Charizard ex",
    rarity: "Ancient Rare",
    value: 48_000,
    image: "https://images.pokemontcg.io/svsh3/125_hires.png",
    acquiredAt: "2h ago",
  },
  {
    vaultId: "v2",
    id: "pk-vault-pikachu-vmax",
    name: "Pikachu VMAX",
    rarity: "Ancient Rare",
    value: 32_000,
    image: "https://images.pokemontcg.io/swsh4/44_hires.png",
    acquiredAt: "5h ago",
  },
  {
    vaultId: "v3",
    id: "pk-vault-mew-ex",
    name: "Mew ex",
    rarity: "Ancient Rare",
    value: 28_500,
    image: "https://images.pokemontcg.io/me1/151_hires.png",
    acquiredAt: "1d ago",
  },
  {
    vaultId: "v4",
    id: "pk-vault-umbreon-vmax",
    name: "Umbreon VMAX",
    rarity: "Ancient Rare",
    value: 42_000,
    image: "https://images.pokemontcg.io/swsh7/215_hires.png",
    acquiredAt: "1d ago",
  },
  {
    vaultId: "v5",
    id: "pk-vault-garchomp-ex",
    name: "Garchomp ex",
    rarity: "Rare",
    value: 4_200,
    image: "https://images.pokemontcg.io/sv4/245_hires.png",
    acquiredAt: "3d ago",
  },
  {
    vaultId: "v6",
    id: "pk-vault-iron-valiant-ex",
    name: "Iron Valiant ex",
    rarity: "Rare",
    value: 3_800,
    image: "https://images.pokemontcg.io/sv4/249_hires.png",
    acquiredAt: "4d ago",
  },
  {
    vaultId: "v7",
    id: "pk-vault-roaring-moon-ex",
    name: "Roaring Moon ex",
    rarity: "Rare",
    value: 3_600,
    image: "https://images.pokemontcg.io/sv4/251_hires.png",
    acquiredAt: "5d ago",
  },
  {
    vaultId: "v8",
    id: "pk-vault-base-charizard",
    name: "Charizard",
    rarity: "Rare",
    value: 12_000,
    image: "https://images.pokemontcg.io/base1/4_hires.png",
    acquiredAt: "1w ago",
  },
];
