/**
 * Generates supabase/seed_upgrader_catalog_targets.sql from frontend pool constants.
 * Run: npx tsx scripts/generateUpgraderSeed.ts
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { GOD_PACK_1999_POOL, LEGENDARY_HUNT_POOL } from "../src/constants/packPokemonPools";
import type { StoreItem } from "../src/types/store";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, "../supabase/seed_upgrader_catalog_targets.sql");
const MIN_GEM_VALUE = 8_000;

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function boxIdForItem(item: StoreItem): string {
  if (item.id.startsWith("pk-god-")) return "god-pack-1999";
  if (item.id.startsWith("pk-hunt-")) return "legendary-hunt";
  return "upgrader-catalog";
}

function buildRows(items: StoreItem[]): string[] {
  return items.map((item, index) => {
    const boxId = boxIdForItem(item);
    return `  (${sqlString(boxId)}, ${sqlString(item.id)}, ${sqlString(item.name)}, ${sqlString(item.rarity)}, ${item.value}, ${sqlString(item.image)}, ${item.probability}, ${index + 1})`;
  });
}

const pool = [...LEGENDARY_HUNT_POOL, ...GOD_PACK_1999_POOL]
  .filter((item) => item.value >= MIN_GEM_VALUE)
  .sort((a, b) => b.value - a.value);

const seen = new Set<string>();
const targets: StoreItem[] = [];
for (const item of pool) {
  if (seen.has(item.id)) continue;
  seen.add(item.id);
  targets.push(item);
}

const sql = `-- Upgrader master catalog targets for process_upgrade_roll lookups.
-- Generated by scripts/generateUpgraderSeed.ts — re-run after changing packPokemonPools.ts
-- Run in Supabase SQL editor after boxes + box_items tables exist.

create table if not exists public.upgrade_catalog_items (
  item_id text primary key,
  item_name text not null,
  store_rarity text not null,
  gem_value integer not null check (gem_value > 0),
  image_url text not null default ''
);

create unique index if not exists box_items_box_id_item_id_uidx
  on public.box_items (box_id, item_id);

insert into public.boxes (
  id,
  name,
  cost,
  description,
  category,
  image_url,
  theme,
  accent_label,
  is_active,
  sort_order
)
values
  (
    'legendary-hunt',
    'Legendary Hunt',
    2500,
    'High variance alternate-art chase pool used for upgrader target validation.',
    'pokemon',
    '',
    'fuchsia',
    'HIGH VARIANCE',
    true,
    4
  ),
  (
    'god-pack-1999',
    'The 1999 God Pack',
    10000,
    'Vintage base-set grail pool used for upgrader target validation.',
    'pokemon',
    '',
    'mystic',
    'CEILING',
    true,
    7
  ),
  (
    'upgrader-catalog',
    'Upgrader Master Catalog',
    0,
    'Canonical gem values for Collection Upgrader targets.',
    'pokemon',
    '',
    'gold',
    'UPGRADER',
    false,
    99
  )
on conflict (id) do update
set
  name = excluded.name,
  cost = excluded.cost,
  description = excluded.description,
  category = excluded.category,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

insert into public.box_items (
  box_id,
  item_id,
  item_name,
  store_rarity,
  gem_value,
  image_url,
  probability,
  sort_order
)
values
${buildRows(targets).join(",\n")}
on conflict (box_id, item_id) do update
set
  item_name = excluded.item_name,
  store_rarity = excluded.store_rarity,
  gem_value = excluded.gem_value,
  image_url = excluded.image_url,
  probability = excluded.probability,
  sort_order = excluded.sort_order;

insert into public.upgrade_catalog_items (
  item_id,
  item_name,
  store_rarity,
  gem_value,
  image_url
)
values
${targets
  .map(
    (item) =>
      `  (${sqlString(item.id)}, ${sqlString(item.name)}, ${sqlString(item.rarity)}, ${item.value}, ${sqlString(item.image)})`,
  )
  .join(",\n")}
on conflict (item_id) do update
set
  item_name = excluded.item_name,
  store_rarity = excluded.store_rarity,
  gem_value = excluded.gem_value,
  image_url = excluded.image_url;
`;

writeFileSync(OUT_PATH, `${sql}\n`);
console.log(`Wrote ${targets.length} upgrader targets to ${OUT_PATH}`);
